version: "3.9"

services:
  redis:
    image: redis:7-alpine
    container_name: hbus-redis
    ports:
      - "6379:6379"
    volumes:
      - E:/CODY/Program/H_Bus/redis_data:/data
    networks:
      - hbus-net

  mariadb:
    image: mariadb:10.11
    container_name: hbus-mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=109109
      - MARIADB_DATABASE=bus_system
    command: ["--port=3307"]
    ports:
      - "3307:3307"
    volumes:
      - E:/CODY/Program/H_Bus/db_data:/var/lib/mysql
      - E:/CODY/Program/H_Bus/bus_system_backup.sql:/docker-entrypoint-initdb.d/bus_system_backup.sql
    networks:
      - hbus-net

  client-api:
    build:
      context: ./Client
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: "/api"
    container_name: hbus-client-api
    ports:
      - "8700:8700"
    environment:
      REDIS_URL: "redis://hbus-redis:6379/0"
      FRONTEND_DEFAULT_URL: "https://a18e95fd77f8.ngrok-free.app"
      LINE_CHANNEL_ID: "2008298748"
      LINE_CHANNEL_SECRET: "8b363c06ac000d89493ee62511790b48"
      APP_SESSION_SECRET: "sd8f7s9df8sdf7"
      Sender_email: "tailin1125@gmail.com"
      Password_email: "ceaa fcfl wubf mjss"
      Host: "hbus-mariadb"
      User: "root"
      Port: "3307"
      Password_SQL: "109109"
      Database: "bus_system"
      MERCHANT_ID: "106952201270001"
      TERMINAL_ID: "70002146"
      STORE_CODE: "e4f76eb8-d236-45fb-984b-92b2d1912492"
      KEY: "3abae022acd6fc873821411c0b402c0fbe90d90bdda295ed15296f8ae465bf8b"
      IV: "12fe9f5e0c3cc7c664894f19ba265050"
      LAYMON: "iqrc.epay365.com.tw"
      TZ: "Asia/Taipei"
      MAIL_SEND_HOUR: "8"
      MAIL_SEND_MIN: "0"
      ALLOWED_RETURN_ORIGINS: "https://a18e95fd77f8.ngrok-free.app,http://localhost:8700"
    depends_on:
      - redis
      - mariadb
    volumes:
      - "E:/SSL:/ssl:ro"
    networks:
      - hbus-net
    command: ["uvicorn", "Server:app", "--host", "0.0.0.0", "--port", "8700", "--reload"]

  bus-api:
    build:
      context: ./my-bus-system
      dockerfile: Dockerfile
    container_name: hbus-bus-api
    ports:
      - "8600:8600"
    environment:
      Host: "192.168.0.126"
      User: "root"
      Port: "3307"
      Password_SQL: "109109"
      Database: "bus_system"
    depends_on:
      - redis
      - mariadb
    volumes:
      - "E:/SSL:/ssl:ro"
    command: ["npm", "run", "serve"]

volumes:
  mysql_data:
  mariadb_data:
